root: true
parser: babel-eslint
env:
  node: true

extends:
  - eslint:recommended
  - prettier

rules:
  array-callback-return: error
  camelcase: error
  consistent-return: error
  eqeqeq: [error, always, 'null': ignore]
  no-constant-condition: [error, checkLoops: false]
  no-control-regex: 0
  no-implicit-globals: error
  no-template-curly-in-string: warn
  no-unused-labels: 0
  no-var: error
  prefer-const: [warn, destructuring: all]

overrides:
  - files: src/**/*.js
    env:
      es6: true
      node: false
  - files:
      - tests/**/*.js
    env:
      es6: true
      jest: true
    rules:
      camelcase: 0
